name: nyc-taxi-pipelines
schedule: monthly
start_date: "2021-01-01"

default_connections:
  google_cloud_platform: "bq-default"

variables:
  taxi_types:
    type: array
    items:
      type: string
    default: ["yellow", "green"]